name: Update README.md

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'  # Only trigger on README.md changes

# Explicitly declare permissions needed for this workflow
permissions:
  contents: write  # Needed for pushing commits

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version:  v2.3.3
          
      - name: Run update_readme.ts script
        run: |
          cd scripts
          deno task run
        continue-on-error: false
          
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code README.md || echo "changes=true" >> $GITHUB_OUTPUT
          
      - name: Commit changes if necessary
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update README.md via GitHub Actions [skip ci]"
          git push
